### ISSUE TITLE
Saving corrupts equipment screen

### ISSUE THREAD

**Issue by Kilicool64** [unknownbrackets/tomatotrans#14]
![Tomato Adventure  en-us 1 0 0 -0](https://user-images.githubusercontent.com/53983097/127619020-cbafe14a-0360-4ff4-900c-877ffc02d988.png)
This is what the equipment screen looks like if I open it right after saving. I'm using mGBA. In case this doesn't happen to everyone, I attached my save file, but note that you have to save again before opening the equipment screen to trigger this glitch.
[Corrupted equipment screen.zip](https://github.com/unknownbrackets/tomatotrans/files/6905882/Corrupted.equipment.screen.zip)

**Comment by Kilicool64** [comment]
I see you just fixed something related to this screen 6 hours ago. I take it this will fix the issue once a new patch is released?

**Comment by Kilicool64** [comment]
Nevermind, I just saw your latest post on the Romhacking.net forums. It seems you have indeed already fixed it. Sorry to bother you.

**Comment by unknownbrackets** [comment]
Thanks for reporting, fixed in 7e92b15.  The Status submenu only has 9 tiles of space but it needs to clear 10 tiles.

-[Unknown]
