### ISSUE TITLE
Minor issue with text in Hotel de Mayo

### ISSUE THREAD

**Issue by Kilicool64** [unknownbrackets/tomatotrans#16]
If you talk to the receptionist in Hotel de Mayo, there's one chunk of text that consists of two lines followed by another line for a Yes/No prompt. If you skip the text rendering process by pressing A or B (which a lot of people probably do all the time, given how painfully slow it is), you won't get to see the first line, which is "So, will you stay for". Here's a screenshot demonstration:
![Tomato Adventure  en-us 1 0 0 -1](https://user-images.githubusercontent.com/53983097/127717399-c5ca4847-075a-4dd4-a3c9-6d392539a24f.png)
![Tomato Adventure  en-us 1 0 0 -2](https://user-images.githubusercontent.com/53983097/127717405-5be1babd-bcd1-47be-abbb-7ad9b80e27bc.png)
This seems unintentional, given that I have yet to encounter any other situation where a single chunk of text covers more than two lines.

**Comment by unknownbrackets** [comment]
Thanks, this is definitely unintentional - a lot of these were caught in editing, but looks like this one was missed.  Thanks for reporting.

I have thought about an optional patch to increase the text draw speed.

-[Unknown]

**Comment by unknownbrackets** [comment]
I've doubled the speed of the text in f902e2e4ac26f0d1c87955d1c2458fdfecf74660.  If you'd like to try running the patch build (just put the original file as ta.gba and run i.bat), does that make it less painfully slow?

I suppose Japanese text was generally less characters, so it wouldn't have felt as slow in Japanese.

-[Unknown]

**Comment by Kilicool64** [comment]
I'm afraid the compilation process seems to have malfunctioned on my end. The resulting ROM has lots of garbled text. I guess I won't be able to try until a patch file is released.

**Comment by unknownbrackets** [comment]
Well, here's a zip with an updated BPS then: [Tomato Adventure [en-us 1.0.0-5-g0bf97fe].zip](https://github.com/unknownbrackets/tomatotrans/files/6913319/Tomato.Adventure.en-us.1.0.0-5-g0bf97fe.zip)

-[Unknown]

**Comment by Kilicool64** [comment]
Okay, that works. And the new text speed seems about right for me, personally.
