### ISSUE TITLE
Can't progress at Soy Bank, glitch also caused DeMille's name to be changed to Dd

### ISSUE THREAD

**Issue by ChooMina** [unknownbrackets/tomatotrans#18]
So I dun broke the game.   Really the only odd thing I did was check every single safe (and battled every enemy) in the room with one of the safes painted on the floor.  (the glitched room)   After realizing I didn't have the two keys to progress (and after saving...) I encountered a glitch that teleports me back to the room I just came from, I was able to go to the menu and use this games equivalent of an escape rope but the glitch still occurred.   I'm pretty sure this is a game breaking glitch and I'm sorry for not knowing what caused it and not having a file from before the incident.  Here's my glitched save:
[TA Glitch.zip](https://github.com/unknownbrackets/tomatotrans/files/7111667/TA.Glitch.zip)

Any help would be greatly appreciated. 

Also while I'm here, I don't know if the Japanese version was like this but the truth/lie puzzle in the Soy Bank threw me off at first because the clues should say "to your right" not "to my right" since they're facing the player.  (Sorry if this sounds like nitpicking)

**Comment by unknownbrackets** [comment]
I loaded your save in mGBA, then went up to see Berri and ultimately got to the part where you see something crashed into a building.  The name is definitely messed up, but I didn't have any issue progressing.

What emulator was this with?  It could be that there's an emulator bug involved here as well.

Here's a version of your save with your name restored:
[TA Glitch - name fixed.zip](https://github.com/unknownbrackets/tomatotrans/files/7111880/TA.Glitch.-.name.fixed.zip)

If you load this save with mGBA, are you able to progress?

It's likely this is a game bug (there was a different but similar bug in Mt. S'creme when you pulled a certain eyeball out), but this patch already fixes a few game bugs as well (as an official localization probably also would have.)  How sure are you that you didn't have a messed up name before this room (I guess you probably would've noticed in battle)?

Thanks for the report.

-[Unknown]

**Comment by ChooMina** [comment]
Thank you for fixing my save.   After reading your post I realized it's probably just a bad rom and progressed fine after redownloading and repatching.  Sorry.

**Comment by unknownbrackets** [comment]
Thanks for the update - glad to hear you're progressing and it was just a bad image downloaded from the cartridge.

I had expected the recommended patching tool to refuse to patch corrupted ROM images... shame this one got through.

-[Unknown]
